{% set name    = "harmonize-async" %}
{% set version = "0.0.1"           %}

package:
  name: {{ name | lower }}
  version: {{ version }}

source:
  git_url: git@github.com:CEMeNT-PSAAP/harmonize.git
  git_rev: "v0.0.1"

requirements:
  build:
    - python
    - setuptools
    - wheel
    - pip
  run:
    - hatchling
    - gxx
    - python>=3.11
    - numba>=0.58.0
    - numpy

test:
  imports:
    - harmonize-async
  requires:
    - pytest

about:
  home: https://github.com/CEMeNT-PSAAP/harmonize
  license: BSD 3-Clause
  summary: 'An async execution framework for GPU.'

outputs:
  - name : harmonize-async
  - type : wheel

build:
  number : 0
  script: pip install . -vv

